In [28]:
# Jupiter  MacOS
# BASE_DIR = "/Users/johnhanratty/Library/CloudStorage/OneDrive-Personal/IRMA_GIT/Kaggle_SignLanguage/asl-signs"
# WORKING_DIR = BASE_DIR
# ARCHIVE_DIR = BASE_DIR
# !pip install nb_black --quiet
# %load_ext lab_black

# Colab
BASE_DIR = "/content/asl-signs"   #"/content/drive/MyDrive/GaggleSignLang/asl-signs"
WORKING_DIR = "/content/asl-work"
ARCHIVE_DIR = "/content/drive/MyDrive/GaggleSignLang"
# !pip install nb_black --quiet
# print('-----ok')
# %load_ext nb_black

# KAGGLE
# BASE_DIR = "/kaggle/input/asl-signs"
# WORKING_DIR = "/kaggle/working/"
# {ARCHIVE_DIR} - "/kaggle/working/"
# !pip install nb_black --quiet --root-user-action=ignore
# %load_ext lab_black

import os
import gc
import shutil
import time

import json
from tqdm import tqdm
import numpy as np
import pandas as pd

import torch
import torch.nn as nn
import torch.nn.functional as F

from torch.utils.data import Dataset, DataLoader
from torchvision import transforms

from sklearn.model_selection import train_test_split
from sklearn.metrics import accuracy_score
from sklearn.preprocessing import normalize

import warnings
warnings.filterwarnings(action='ignore')

LANDMARK_FILES_DIR = f'{BASE_DIR}/train_landmark_files'
TRAIN_FILE = f"{BASE_DIR}/train.csv"

FRAMES_OUT = 8 #16 # 16
PTS_IN_FRAME = 115
DIMC = [0,1,2]
DIMS = len(DIMC)

  
HANDIDX = {"WRIST":0, "THUMB_CMC":1, "THUMB_MCP":2,     "THUMB_IP":3,          "THUMB_TIP":4,
        "INDEX_FINGER_MCP":5, "INDEX_FINGER_PIP":6,  "INDEX_FINGER_DIP":7,  "INDEX_FINGER_TIP":8,
        "MIDDLE_FINGER_MCP":9,"MIDDLE_FINGER_PIP":10,"MIDDLE_FINGER_DIP":11,"MIDDLE_FINGER_TIP":12,
        "RING_FINGER_MCP":13, "RING_FINGER_PIP":14,  "RING_FINGER_DIP":15,  "RING_FINGER_TIP":16,
        "PINKY_FINGER_MCP":17,"PINKY_FINGER_PIP":18,  "PINKY_FINGER_DIP":19,"PINKY_FINGER_TIP":20}

POSEIDX = {"NOSE":0,        "LEFT_EYE_INNER":1,"LEFT_EYE":2,   "LEFT_EYE_OUTER":3, "RIGHT_EYE_INNER":4, "RIGHT_EYE":5,      "RIGHT_EYE_OUTER":6,
        "LEFT_EAR":7,    "RIGHT_EAR":8,     "MOUTH_LEFT":9, "MOUTH_RIGHT":10,   "LEFT_SHOULDER":11,  "RIGHT_SHOULDER":12,
        "LEFT_ELBOW":13, "RIGHT_ELBOW":14,  "LEFT_WRIST":15, "RIGHT_WRIST":16, 
        "LEFT_PINKY":17, "RIGHT_PINKY":18,  "LEFT_INDEX":19,"RIGHT_INDEX":20,   "RIGHT_THUMB":21,    "LEFT_THUMB":22,
        "LEFT_HIP":23,   "RIGHT_HIP":24,    "LEFT_KNEE":25, "RIGHT_KNEE":26,    "LEFT_ANKLE":27,     "RIGHT_ANKLE":28,
        "LEFT_HEEL":29,  "RIGHT_HEEL":30,   "LEFT_FOOT_INDEX":31, "RIGHT_FOOT_INDEX":32}

LIPSIDX = [61, 185, 40, 39, 37, 0, 267, 269, 270, 409, 291, 78, 191, 80, 81, 82, 13, 312, 311, 310, 415, 308, 95, 88, 178, 87, 14, 317, 402, 318, 324, 146, 91, 181, 84, 17, 314, 405, 321, 375]
LIPSIDX_sm = [185, 39, 0,  269,  409,  78,  80,  82,  312,  310,  308,  88,  87,  317,  318,  146,  181,  17,  405, 375]


# need to rerun parquet processing to grab data points
#LIPSIDX1 = [12, 268,271,272,407, 293, 325,319,403,316,15,86,179,89,96,62, 183,42,41,38]

METALEN = len(LIPSIDX) + len(POSEIDX) + 2 * len(HANDIDX)

def PRIM_HAND(idx): return(40 + HANDIDX[idx])
def POSE(idx):  return(40 + 21 + POSEIDX[idx])
def SEC_HAND(idx):  return(40 + 21 + 33 + HANDIDX[idx])

print(POSE("NOSE"))
print(SEC_HAND("WRIST"))
METALEN
    
import pickle
with open(f"/content/drive/MyDrive/GaggleSignLang/truth_nan.pkl", 'rb') as handle:
    nan_truth = pickle.load(handle)

print('done')

if torch.cuda.is_available():
  device = torch.device("cuda")
  print("++++using GPU++++")
else:
  device = torch.device("cpu")
  print("++++using CPU++++")

61
94
done
++++using CPU++++

In [12]:
# GET FEATURE FILES FROM GDRIVE 
# COLAB ONLY - MOVE FEATURE FILES TO WORKING DIRECTORY
# 
import os
import gc
import shutil

if os.getenv("COLAB_RELEASE_TAG") and not os.path.exists(WORKING_DIR):
  !mkdir '/content/asl-work'

if os.getenv("COLAB_RELEASE_TAG"):
    #shutil.copy(f"/content/drive/MyDrive/GaggleSignLang/feature_prep64.npy", f"{WORKING_DIR}")
    #shutil.copy(f"/content/drive/MyDrive/GaggleSignLang/feature_prep64xy.npy", f"{WORKING_DIR}")
    #shutil.copy(f"/content/drive/MyDrive/GaggleSignLang/feature_prep64xz.npy", f"{WORKING_DIR}")

    shutil.copy(f"/content/drive/MyDrive/GaggleSignLang/feature_data{FRAMES_OUT}.npy", f"{WORKING_DIR}")
    shutil.copy(f"/content/drive/MyDrive/GaggleSignLang/feature_labels.npy", f"{WORKING_DIR}")
    shutil.copy(f"/content/drive/MyDrive/GaggleSignLang/sign_to_prediction_index_map.json", f"{WORKING_DIR}")
    # LOAD POLYGON DATA - FRAMES

In [29]:
# GET TRUTH FROM TESTY
shutil.copy(f"/content/drive/MyDrive/GaggleSignLang/feature_data{FRAMES_OUT}.npy", f"{WORKING_DIR}")
datax = np.load(f"{ARCHIVE_DIR}/feature_data{FRAMES_OUT}.npy")
datay = np.load(f"{ARCHIVE_DIR}/feature_labels.npy") 

trainx, testx, trainy, testy, _, framesy = train_test_split(datax, datay, nan_truth, test_size=0.15, random_state=42)

In [30]:
import pickle
with open(f"/content/drive/MyDrive/GaggleSignLang/pred_tsai1.pkl", 'rb') as f1:
       preds = pickle.load(f1)

with open(f"/content/drive/MyDrive/GaggleSignLang/pred_tsai_probt.pkl", 'rb') as f2:
        prob_tran = pickle.load(f2)

with open(f"/content/drive/MyDrive/GaggleSignLang/pred_tsai_probi.pkl", 'rb') as f3:
       prob_in = pickle.load(f3)

with open(f"/content/drive/MyDrive/GaggleSignLang/prob_cnn.pkl", 'rb') as f3:
       prob_cnn = pickle.load(f3)

# FIX TRUTH
preds['truth']=testy.astype(int)
preds.predi = preds.predi.astype(float).astype(int)
preds.predt = preds.predt.astype(float).astype(int)

sm = nn.Softmax(dim=1) 
prob_cnns = sm(torch.Tensor(prob_cnn)).numpy()
preds['predc'] = np.argmax(prob_cnns, axis=1)

preds["probi"] = prob_in.numpy().max(axis=1)
preds["probt"] = prob_tran.numpy().max(axis=1)
preds["probc"] = prob_cnns.max(axis=1)

In [31]:
preds.head()

       truth  nans    idx  predt  predi  predc     probi     probt     probc
80305    206    20  80305    247    206     78  0.627538  0.711359  0.384106
80306     20    42  80306     20     96     96  0.426852  0.784956  0.486097
80307    178    16  80307     26    178    200  0.641837  0.267397  0.072054
80308    114    50  80308    114    114    114  0.888171  0.965296  0.977423
80309    221    64  80309    221    221    221  0.954264  0.982313  0.877944

In [32]:
print("SINGLE MODEL ACCURACY")
print("Tran", np.mean(preds['truth'] == preds['predt']), 
      "In", np.mean(preds['truth'] == preds['predi']),
      "CNN",  np.mean(preds['truth'] == preds['predc']))

SINGLE MODEL ACCURACY
Tran 0.735182049110923 In 0.7398391193903472 CNN 0.6808495625176404

In [33]:
# Choose highest prob prediction from ALL models
def highest_prob(row):
  if (row['probi'] > row['probt']) & (row['probi'] > row['probc']):
    return row['predi']
  elif row['probt'] > row['probc']:
    return row['predt']
  else:
    return row['predc']

print("ALL MODELS")
preds["hpall"] = preds.apply(lambda row: highest_prob(row), axis=1)

print(np.mean(preds.truth==preds.hpall))

ALL MODELS
0.749435506632797

In [34]:
# Choose highest prob prediction from PROBI & PROBT
def highest_prob(row):
  if (row['probi'] > row['probt']):
    return row['predi']
  else:
    return row['predt']

preds["hpit"] = preds.apply(lambda row: highest_prob(row), axis=1)
print("I & T Models")
print(np.mean(preds.truth==preds.hpit))

I & T Models
0.7452018063787751

In [35]:
# Choose highest prob prediction from PROBI & PROBC
def highest_prob(row):
  if (row['probi'] > row['probc']):
    return row['predi']
  else:
    return row['predc']

preds["hpic"] = preds.apply(lambda row: highest_prob(row), axis=1)
print("i & c Models")
print(np.mean(preds.truth==preds.hpic))

i & c Models
0.7444961896697714

In [36]:
# Choose highest prob prediction from PROBT & PROBC
def highest_prob(row):
  if (row['probt'] > row['probc']):
    return row['predt']
  else:
    return row['predc']

preds["hptc"] = preds.apply(lambda row: highest_prob(row), axis=1)

print(np.mean(preds.truth==preds.hptc))

0.7353231724527237

In [24]:
preds['incep'] = preds.truth == preds.predi
preds['trans'] = preds.truth == preds.predt
preds['cnnag'] = preds.truth == preds.predc

In [25]:
preds.head()

,truth,nans,idx,predt,predi,predc,probi,probt,probc,hpall,hpit,hpic,hptc,incep,trans,cnnag
80305,206,20,80305,247,206,247,0.627538,0.711359,0.735845,247.0,247.0,247.0,247.0,True,False,False
80306,20,42,80306,20,96,96,0.426852,0.784956,0.357823,20.0,20.0,96.0,20.0,False,True,False
80307,178,16,80307,26,178,151,0.641837,0.267397,0.042810,178.0,178.0,178.0,26.0,True,False,False
80308,114,50,80308,114,114,114,0.888171,0.965296,0.973645,114.0,114.0,114.0,114.0,True,True,True
80309,221,64,80309,221,221,221,0.954264,0.982313,0.869086,221.0,221.0,221.0,221.0,True,True,True

In [26]:
fcnt = preds[preds.nans < 6].groupby('nans').agg(iacc = ("incep","mean"),
                                                 cnt = ("idx","count"))

fcnt

          iacc  cnt
nans
0     0.833333    6
1     0.750000    8
2     0.863636   22
3     0.666667   21
4     0.689655   29
5     0.775000   40

In [27]:
preds[preds.nans < 4].groupby('truth').agg(iacc = ("incep","mean"),
                                cnt = ("idx","count"))

           iacc  cnt
truth
9      1.000000    1
19     1.000000    1
22     1.000000    1
37     1.000000    1
38     1.000000    1
44     1.000000    1
48     1.000000    1
51     1.000000    1
62     1.000000    2
69     1.000000    1
72     1.000000    1
77     1.000000    1
82     1.000000    1
83     0.000000    1
89     0.000000    1
93     1.000000    1
94     0.000000    1
98     0.000000    1
100    1.000000    1
102    1.000000    1
106    1.000000    1
111    1.000000    1
123    1.000000    1
130    1.000000    1
131    0.000000    1
132    1.000000    1
133    1.000000    1
135    1.000000    1
149    1.000000    1
159    1.000000    1
161    0.666667    3
163    1.000000    1
166    0.000000    1
167    1.000000    1
174    1.000000    1
177    1.000000    2
179    1.000000    1
188    1.000000    1
198    0.000000    1
202    1.000000    1
207    0.000000    1
216    0.000000    1
220    1.000000    1
227    0.500000    2
234    1.000000    1
235    0.000000    1
236    0.500000    2
238    1.000000    1
243    1.000000    1
245    1.000000    1
246    1.000000    1

In [ ]:
# ENSEMBLE VOTING
print("2 out of 3",)